name: Docs

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    # Set up operating system
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Apt Requirements
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update && \
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y sphinx python3-sphinx

      - name: Checkout
        uses: actions/checkout@v4.1.1
  
      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install --with dev

      - name: Build documentation
        run: poetry run make html --directory docs/

      - name: Upload page artficat
        uses: actions/upload-artifact@v4
        with:
          name: pymeca-docs-artifact
          path: docs/_build/html
  
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artficat
        uses: actions/download-artifact@v4
        with:
          name: pymeca-docs-artifact
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4